@startuml 'how_pandadoc_parts.puml' 

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

!theme amiga

skinparam NoteBackgroundColor #FFF7E3
skinparam NoteFontColor #47B972
skinparam NoteFontName Arial

folder "API" {
  [**Authentication**\nAPI-Key\nOAuth 2.0 Bearer Token]
  cloud {
    [**Documents**]
      note bottom #FFF7E3
        inside Text Blocks, 
        using brackets syntax 
        [//VariableName//]
      end note
    [**Templates**]
      note bottom #FFF7E3 
        List,
		Details,
		Delete
      end note
    [**Contacts**]
    [**Forms**]
    [**Folders**]
    [**API-Logs**]
    [**CLI**]
  }
}

@enduml

