@startuml 'how_pandadoc_parts.puml' 

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

!theme amiga

skinparam NoteBackgroundColor #FFF7E3
skinparam NoteFontColor #47B972
skinparam NoteFontName Arial

package JSON {

folder data {
  [id]
  [name]
  [status]
  [created_by]
  [dates]
  [metadadta]
  [tags]
  [pricing table]
  package tokens {
	artifact Variables#gray
	Variables --> [v1]
	Variables --> [v2]
	Variables --> [vn]
  }
  package fields {
	artifact FillableFields#gray
	FillableFields --> [f1]
	FillableFields --> [f2]
	FillableFields --> [fn]
  }
  package recipients {
	artifact Roles#gray
	Roles --> [r1]
	Roles --> [r2]
	Roles --> [rn]
  }
  v2 -[hidden]down- FillableFields
}

folder event {
  [**document_state_changed**//, or//\n**recipient_completed**//, or//\ndocument_deleted//, or//\ndocument_updated//, or//\ndocument_creation_failed]
}

}

@enduml

