@startuml 'how_datda_flow.puml' 

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

skinparam sequenceMessageAlign center

  Box "UpStreamSystem" #E8F2FE
    database UpStreamData order 1
  end Box

  Box "PandaDoc" #EAEFEB
	queue Templates order 2
	participant Documents order 3
	queue Notifications order 4
  end Box

  Box "DownStreamSystem" #F5F1EE
    database DownStreamData order 5
  end Box

	UpStreamData x-[#red]>o Templates : **INBOUND**\n//<data/>//

	Templates --[#orange]> Documents
	Documents --[#orange]> Notifications : Status Change <&bell>

	Notifications x-[#red]>o DownStreamData : **OUTBOUND**\n//<data/>//

@enduml

