@startuml 'title'

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

autonumber

  Box Greenhouse
    actor User order 1
    database Offer order 2
  end Box

  Box PandaDoc #WhiteSmoke
    participant Document order 5
    participant ProcessAutomations order 6
  end Box

  group#LightGray #FFF7E3 monitor
    ProcessAutomations o<[#red]- Document : Status Changes (Declined or Completed)
    Offer <--[#red]o ProcessAutomations: Update Stage
  end

@enduml