@startuml 'title'

!include https://raw.githubusercontent.com/jimbarry0406/pandadoc/main/puml/pandadoc_defaults.puml

autonumber

  Box PandaDoc #WhiteSmoke
    participant Template order 2
    participant Document order 1
  end Box

  Box iPaaS
    participant Zap order 3
  end Box

  group#LightGray #FFF7E3 monitor
    Document -[#red]>o Zap: Doc<sup>1</sup> Status Changes (Sent or Completed)
    Zap o-[#red]> Template: Select Template

	autonumber stop
	  Template --[#red]> Document: <&sun> Create New Doc<sup>2</sup>
	autonumber resume
  end

@enduml